spring.application.name=tere-verde
spring.datasource.url=jdbc:postgresql://localhost/tere-verde
spring.datasource.username=postgres
spring.datasource.password=#abc123#
spring.datasource.driver-class-name=org.postgresql.Driver